### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by luceat-lux-vestra** [manuelgustavo/copy-commando#5]
I'm looking for a free alternative to TeraCopy.

I didn't try this yet, can you tell me more about the state of this project?

And what makes this faster than TeraCopy?

Can I use this for the daily driver without worries?

Thanks.

**Comment by manuelgustavo** [comment]
No, it isn't production ready.

Sorry, I haven't had the time to continue this project.

Regards,
Manuel
